### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by RailsCod3rFuture** [erdostom/devise-argon2#1]
Do you have a solution for building the gem on a windows based platform?

Installing argon2 0.1.4 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
C:/Ruby217/Ruby21/bin/ruby.exe extconf.rb
```

make "DESTDIR=" clean
rm -f tests libargon2_wrap.dll

make "DESTDIR="
gcc -std=c89 -pthread -O3 -Wall -g -march=native -shared -Wl,--out-implib,libargon2_wrap.dll.a ../phc-winner-argon2/src/argon2.c ../phc-winner-argon2/src/core.c ../phc-winner-argon2/src/blake2/blake2b.c ../phc-winner-argon2/src/thread.c ../phc-winner-argon2/src/encoding.c argon_wrap.c ../phc-winner-argon2/src/opt.c -o libargon2_wrap.dll
c:/ruby217/devkit3/mingw/bin/../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/lib/../lib/libpthread.dll.a: could not read symbols: Archive has no index; run ranlib to add one
collect2.exe: error: ld returned 1 exit status
make: **\* [libs] Error 1

make failed, exit code 2

An error occurred while installing argon2 (0.1.4), and Bundler cannot continue.
Make sure that `gem install argon2 -v '0.1.4'` succeeds before bundling.

**Comment by erdostom** [comment]
Hi 

This seems to an issue with the underlying `argon2` gem. May be worth creating an issue on their page: https://github.com/technion/ruby-argon2

I'm on a Mac, so I can't debug this well myself.

**Comment by erdostom** [comment]
It may worth looking into something like Docker or creating a virtual machine so you can code Rails in a *NIX environment that is similar to the server that will actually host your app.
