### ISSUE TITLE
devise-encryptable and salts/pepper in argon2

### ISSUE THREAD

**Issue by moritzhoeppner** [erdostom/devise-argon2#11]
Hi there,

as far as I understand it, devise-encryptable deals mainly with managing salts for legacy algorithms. Argon2 on the other hand has a built-in salt that is saved in the encrypted_password field (see https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md). So I think it might be a good idea to get rid of the devise-encryptable dependency altogether.

I played a little with a fork of this repository and it seems to be as simple as this: https://github.com/moritzhoeppner/devise-argon2/commit/a8b4542d7c0f1a67ff9b9533820bd4b858f3e73a

Would you be interested in general in doing something like this? I'd be happy to make a pull request but I wanted to check before investing more time in this idea.

At this occasion we could make a few more improvements:
- Don't simply concatenate password and pepper but give the pepper as 'secret' parameter to Argon2::Password.new.
- Make the Argon2 parameters accessible via devise config.
- Allow migrating from bcrypt/different parameter values for argon2 by updating encrypted_password in valid_password? if the given password is valid.

**Comment by erdostom** [comment]
Hi @moritzhoeppner I think your approach is great! Do you want to make a PR?

**Comment by moritzhoeppner** [comment]
Hi @erdostom great, I'm working on it :)
