### ISSUE TITLE
Changing work factors in paranoid mode

### ISSUE THREAD

**Issue by moritzhoeppner** [erdostom/devise-argon2#17]
Hi @erdostom 

If `Devise.paranoid` is set to true, Devise makes sure that a given password is hashed whether or not a record with the given email is found. Hence response times are always the same and users can't infer if the account exists without having the password. (https://github.com/heartcombo/devise/blob/e2242a95f3bb2e68ec0e9a064238ff7af6429545/lib/devise/strategies/database_authenticatable.rb#L22)

I'm afraid we break this feature when we update work factors.

- When increasing work factors: Password verification for existing records (which have password hashes with the old work factors) takes less time than the hashing due to Devise's paranoid feature.
- When decreasing work factors: Password verification for existing records takes more time than the hashing due to Devise's paranoid feature.

I'd propose the following solution: We offer a new argon_options key, say `:min_hashing_time`, and we make sure that the hashing in `password_digest` and `verify_password` runs at least as long as the value of this option.

I suppose that the usual use case is increasing work factors. In this case, `min_hashing_time` should be set to the execution time of the hashing procedure with the new work factors. For this we can write a class method like `set_min_hashing_time`. Then the  feature could be used like this:

```
class User < ApplicationRecord
  devise :database_authenticatable,
    :argon2,
    argon2_options: { [updated work factors] }

  set_min_hashing_time
end
```

(On second thought: It is probably not a good idea to set `min_hashing_time` like this. If the server is under heavy load, we might over-estimate the required hashing time, leading to performance problems and DoS opportunities. It might be better to always hard-code the value of `min_hashing_time`.)

I have implemented this solution (https://github.com/erdostom/devise-argon2/commit/4212d433711c3f2377deae0012b5cd7904f62d68) and also wrote some tests to make the problem clear (https://github.com/erdostom/devise-argon2/commit/e94cf79fa7cf9fa804d69c2047f6f5c43a4fe09a). However, the tests are flaky since execution time varies so I think we should not use them.

If you like the solution, I'll make a proper pull request and also write something about it in the README.

**Comment by erdostom** [comment]
Hi @moritzhoeppner 

This is an interesting problem related to not just work factors, but any situation where multiple auth methods are used. For example switching from bcrypt, or even the old implementation of Argon2.

So I think this problem is more general than just Argon2 -- it might make sense to put this is another gem or even as an extension of Devise.paranoid.

Meanwhile, since changing work factors does break Devise.paranoid, we should call this out in the docs. One (drastic) solution that fixes this might be resetting all user's passwords so they have to use the new scheme.

**Comment by moritzhoeppner** [comment]
Hi @erdostom 

You're right, the problem is not just related to work factors. As far as I can see, my solution works also when migrating from bcrypt or devise-argon2 v1.

And I think I mischaracterized the situation in another way: We don't break the paranoid feature. This problem seems to be present in Devise itself. When you change the `stretches` option, you are in the same situation. (I have to verify this, but at first glance it seems like it.) So I think we don't need to update the docs.

I'm not convinced that a separate gem is the best way to go since the relevant changes are only a few lines and I'd rather not force people into installing more gems than necessary/installing from more sources than necessary. But it is probably a good idea to change devise instead of devise-argon2.

Thanks for your thoughts! If you agree, we can close the issue for now as it does seem to be an issue of devise itself.
