### ISSUE TITLE
Argon2 is not encryption

### ISSUE THREAD

**Issue by paragonie-scott** [erdostom/devise-argon2#2]
[Hashing is not encryption](https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded).

In general, you don't _encrypt_ passwords, you use a _password hashing_ algorithm. The current terminology is incredibly likely to muddy the waters for your users.

**Comment by erdostom** [comment]
Great points @paragonie-scott. Unfortunately devise uses this terminology and this plugin is meant to use devise's interface / work with https://github.com/plataformatec/devise-encryptable
