### ISSUE TITLE
Redundant salt

### ISSUE THREAD

**Issue by lancecarlson** [erdostom/devise-argon2#6]
Not that it is a huge issue, but the argon2 gem is already salting the password. If you do a search on the argon gem for salt_do_not_supply, you can see the line where you can ignore this step. Currently with this gem we're double salting. Might make sense to either defer to this gem for salting and then we don't need the extra migration that devise_encryptor gem wants? Is it possible to not use that migration?

**Comment by erdostom** [comment]
Thank you, this is a valid point. Feel free to supply `nil` for salt or pepper and the gem will still work. As redundant as these parameters are, devise requires them.
